namespace Panomi.UI.Helpers;

/// <summary>
/// Simple localization helper - just dictionaries of strings.
/// </summary>
public static class Loc
{
    private static string _currentLanguage = "en-US";
    
    public static string CurrentLanguage => _currentLanguage;
    
    private static readonly Dictionary<string, Dictionary<string, string>> _strings = new()
    {
        ["en-US"] = new()
        {
            ["ScanButton"] = "Scan Launchers & Games",
            ["LaunchButton"] = "Launch",
            ["LaunchingButton"] = "Launching...",
            ["Library"] = "Library",
            ["FilterAll"] = "All",
            ["FilterLaunchers"] = "Launchers",
            ["FilterGames"] = "Games",
            ["FilterButton"] = "Filter",
            ["ResetFilters"] = "Reset filters",
            ["SearchPlaceholder"] = "Search games...",
            ["TypeLauncher"] = "Launcher",
            ["TypeGame"] = "Game",
            ["FullscreenMode"] = "Fullscreen",
            ["StartWithWindows"] = "Start with Windows",
            ["MinimizeToTray"] = "Quick Launch",
            ["QuickLaunchInfo"] = "Keeps PANOMI running so it opens instantly",
            ["LanguageSetting"] = "Language",
            ["StatTotal"] = "Total",
            ["StatLaunchers"] = "Launchers",
            ["StatGames"] = "Games",
            ["UpdateAvailable"] = "Update Available",
            ["WebConsole"] = "Console",
            ["WebLiveStreaming"] = "Live Streaming",
            ["WebMisc"] = "Misc",
            ["WebPC"] = "PC",
            ["WebSocialMedia"] = "Social Media",
            ["WebTVStreaming"] = "TV Streaming",
            ["WebSupport"] = "Support PANOMI"
        },
        ["es"] = new()
        {
            ["ScanButton"] = "Buscar Launchers y Juegos",
            ["LaunchButton"] = "Iniciar",
            ["LaunchingButton"] = "Iniciando...",
            ["Library"] = "Biblioteca",
            ["FilterAll"] = "Todos",
            ["FilterLaunchers"] = "Launchers",
            ["FilterGames"] = "Juegos",
            ["FilterButton"] = "Filtrar",
            ["ResetFilters"] = "Reiniciar filtros",
            ["SearchPlaceholder"] = "Buscar...",
            ["TypeLauncher"] = "Launcher",
            ["TypeGame"] = "Juego",
            ["FullscreenMode"] = "Pantalla completa",
            ["StartWithWindows"] = "Iniciar con Windows",
            ["MinimizeToTray"] = "Inicio Rápido",
            ["QuickLaunchInfo"] = "Mantiene PANOMI activo para abrir al instante",
            ["LanguageSetting"] = "Idioma",
            ["StatTotal"] = "Total",
            ["StatLaunchers"] = "Launchers",
            ["StatGames"] = "Juegos",
            ["WebConsole"] = "Consola",
            ["WebLiveStreaming"] = "Streaming en Vivo",
            ["WebMisc"] = "Varios",
            ["WebPC"] = "PC",
            ["WebSocialMedia"] = "Redes Sociales",
            ["WebTVStreaming"] = "Streaming de TV",
            ["WebSupport"] = "Apoyar a PANOMI"
        },
        ["pt-BR"] = new()
        {
            ["ScanButton"] = "Buscar Launchers e Jogos",
            ["LaunchButton"] = "Iniciar",
            ["LaunchingButton"] = "Iniciando...",
            ["Library"] = "Biblioteca",
            ["FilterAll"] = "Todos",
            ["FilterLaunchers"] = "Launchers",
            ["FilterGames"] = "Jogos",
            ["FilterButton"] = "Filtrar",
            ["ResetFilters"] = "Resetar filtros",
            ["SearchPlaceholder"] = "Buscar...",
            ["TypeLauncher"] = "Launcher",
            ["TypeGame"] = "Jogo",
            ["FullscreenMode"] = "Tela cheia",
            ["StartWithWindows"] = "Iniciar com Windows",
            ["MinimizeToTray"] = "Início Rápido",
            ["QuickLaunchInfo"] = "Mantém o PANOMI ativo para abrir instantaneamente",
            ["LanguageSetting"] = "Idioma",
            ["StatTotal"] = "Total",
            ["StatLaunchers"] = "Launchers",
            ["StatGames"] = "Jogos",
            ["WebConsole"] = "Console",
            ["WebLiveStreaming"] = "Transmissão ao Vivo",
            ["WebMisc"] = "Diversos",
            ["WebPC"] = "PC",
            ["WebSocialMedia"] = "Redes Sociais",
            ["WebTVStreaming"] = "Streaming de TV",
            ["WebSupport"] = "Apoiar PANOMI"
        },
        ["fr"] = new()
        {
            ["ScanButton"] = "Rechercher Launchers et Jeux",
            ["LaunchButton"] = "Lancer",
            ["LaunchingButton"] = "Lancement...",
            ["Library"] = "Bibliothèque",
            ["FilterAll"] = "Tous",
            ["FilterLaunchers"] = "Launchers",
            ["FilterGames"] = "Jeux",
            ["FilterButton"] = "Filtrer",
            ["ResetFilters"] = "Réinitialiser filtres",
            ["SearchPlaceholder"] = "Rechercher...",
            ["TypeLauncher"] = "Launcher",
            ["TypeGame"] = "Jeu",
            ["FullscreenMode"] = "Plein écran",
            ["StartWithWindows"] = "Démarrer avec Windows",
            ["MinimizeToTray"] = "Lancement Rapide",
            ["QuickLaunchInfo"] = "Garde PANOMI actif pour une ouverture instantanée",
            ["LanguageSetting"] = "Langue",
            ["StatTotal"] = "Total",
            ["StatLaunchers"] = "Launchers",
            ["StatGames"] = "Jeux",
            ["WebConsole"] = "Console",
            ["WebLiveStreaming"] = "Streaming en Direct",
            ["WebMisc"] = "Divers",
            ["WebPC"] = "PC",
            ["WebSocialMedia"] = "Réseaux Sociaux",
            ["WebTVStreaming"] = "Streaming TV",
            ["WebSupport"] = "Soutenir PANOMI"
        },
        ["de"] = new()
        {
            ["ScanButton"] = "Launcher und Spiele Suchen",
            ["LaunchButton"] = "Starten",
            ["LaunchingButton"] = "Starten...",
            ["Library"] = "Bibliothek",
            ["FilterAll"] = "Alle",
            ["FilterLaunchers"] = "Launcher",
            ["FilterGames"] = "Spiele",
            ["FilterButton"] = "Filter",
            ["ResetFilters"] = "Filter zurücksetzen",
            ["SearchPlaceholder"] = "Suchen...",
            ["TypeLauncher"] = "Launcher",
            ["TypeGame"] = "Spiel",
            ["FullscreenMode"] = "Vollbild",
            ["StartWithWindows"] = "Mit Windows starten",
            ["MinimizeToTray"] = "Schnellstart",
            ["QuickLaunchInfo"] = "Hält PANOMI aktiv für sofortiges Öffnen",
            ["LanguageSetting"] = "Sprache",
            ["StatTotal"] = "Gesamt",
            ["StatLaunchers"] = "Launcher",
            ["StatGames"] = "Spiele",
            ["WebConsole"] = "Konsole",
            ["WebLiveStreaming"] = "Live-Streaming",
            ["WebMisc"] = "Sonstiges",
            ["WebPC"] = "PC",
            ["WebSocialMedia"] = "Soziale Medien",
            ["WebTVStreaming"] = "TV-Streaming",
            ["WebSupport"] = "PANOMI unterstützen"
        },
        ["it"] = new()
        {
            ["ScanButton"] = "Cerca Launcher e Giochi",
            ["LaunchButton"] = "Avvia",
            ["LaunchingButton"] = "Avvio...",
            ["Library"] = "Libreria",
            ["FilterAll"] = "Tutti",
            ["FilterLaunchers"] = "Launcher",
            ["FilterGames"] = "Giochi",
            ["FilterButton"] = "Filtra",
            ["ResetFilters"] = "Reimposta filtri",
            ["SearchPlaceholder"] = "Cerca...",
            ["TypeLauncher"] = "Launcher",
            ["TypeGame"] = "Gioco",
            ["FullscreenMode"] = "Schermo intero",
            ["StartWithWindows"] = "Avvia con Windows",
            ["MinimizeToTray"] = "Avvio Rapido",
            ["QuickLaunchInfo"] = "Mantiene PANOMI attivo per aprire istantaneamente",
            ["LanguageSetting"] = "Lingua",
            ["StatTotal"] = "Totale",
            ["StatLaunchers"] = "Launcher",
            ["StatGames"] = "Giochi",
            ["WebConsole"] = "Console",
            ["WebLiveStreaming"] = "Streaming Live",
            ["WebMisc"] = "Varie",
            ["WebPC"] = "PC",
            ["WebSocialMedia"] = "Social Media",
            ["WebTVStreaming"] = "Streaming TV",
            ["WebSupport"] = "Supporta PANOMI"
        },
        ["ko"] = new()
        {
            ["ScanButton"] = "런처 및 게임 검색",
            ["LaunchButton"] = "실행",
            ["LaunchingButton"] = "실행 중...",
            ["Library"] = "라이브러리",
            ["FilterAll"] = "전체",
            ["FilterLaunchers"] = "런처",
            ["FilterGames"] = "게임",
            ["FilterButton"] = "필터",
            ["ResetFilters"] = "필터 초기화",
            ["SearchPlaceholder"] = "검색...",
            ["TypeLauncher"] = "런처",
            ["TypeGame"] = "게임",
            ["FullscreenMode"] = "전체 화면",
            ["StartWithWindows"] = "Windows 시작 시 실행",
            ["MinimizeToTray"] = "빠른 실행",
            ["QuickLaunchInfo"] = "PANOMI를 활성 상태로 유지하여 즉시 열기",
            ["LanguageSetting"] = "언어",
            ["StatTotal"] = "전체",
            ["StatLaunchers"] = "런처",
            ["StatGames"] = "게임",
            ["WebConsole"] = "콘솔",
            ["WebLiveStreaming"] = "라이브 스트리밍",
            ["WebMisc"] = "기타",
            ["WebPC"] = "PC",
            ["WebSocialMedia"] = "소셜 미디어",
            ["WebTVStreaming"] = "TV 스트리밍",
            ["WebSupport"] = "PANOMI 후원"
        },
        ["ja"] = new()
        {
            ["ScanButton"] = "ランチャーとゲームをスキャン",
            ["LaunchButton"] = "起動",
            ["LaunchingButton"] = "起動中...",
            ["Library"] = "ライブラリ",
            ["FilterAll"] = "すべて",
            ["FilterLaunchers"] = "ランチャー",
            ["FilterGames"] = "ゲーム",
            ["FilterButton"] = "フィルター",
            ["ResetFilters"] = "フィルターをリセット",
            ["SearchPlaceholder"] = "検索...",
            ["TypeLauncher"] = "ランチャー",
            ["TypeGame"] = "ゲーム",
            ["FullscreenMode"] = "フルスクリーン",
            ["StartWithWindows"] = "Windows起動時に開始",
            ["MinimizeToTray"] = "クイック起動",
            ["QuickLaunchInfo"] = "PANOMIを常駐させて即座に起動",
            ["LanguageSetting"] = "言語",
            ["StatTotal"] = "合計",
            ["StatLaunchers"] = "ランチャー",
            ["StatGames"] = "ゲーム",
            ["WebConsole"] = "コンソール",
            ["WebLiveStreaming"] = "ライブ配信",
            ["WebMisc"] = "その他",
            ["WebPC"] = "PC",
            ["WebSocialMedia"] = "ソーシャルメディア",
            ["WebTVStreaming"] = "動画配信",
            ["WebSupport"] = "PANOMIを支援"
        },
        ["zh-CN"] = new()
        {
            ["ScanButton"] = "扫描启动器和游戏",
            ["LaunchButton"] = "启动",
            ["LaunchingButton"] = "启动中...",
            ["Library"] = "游戏库",
            ["FilterAll"] = "全部",
            ["FilterLaunchers"] = "启动器",
            ["FilterGames"] = "游戏",
            ["FilterButton"] = "筛选",
            ["ResetFilters"] = "重置筛选",
            ["SearchPlaceholder"] = "搜索...",
            ["TypeLauncher"] = "启动器",
            ["TypeGame"] = "游戏",
            ["FullscreenMode"] = "全屏",
            ["StartWithWindows"] = "随Windows启动",
            ["MinimizeToTray"] = "快速启动",
            ["QuickLaunchInfo"] = "保持PANOMI运行以便即时打开",
            ["LanguageSetting"] = "语言",
            ["StatTotal"] = "总计",
            ["StatLaunchers"] = "启动器",
            ["StatGames"] = "游戏",
            ["WebConsole"] = "主机",
            ["WebLiveStreaming"] = "直播",
            ["WebMisc"] = "其他",
            ["WebPC"] = "电脑",
            ["WebSocialMedia"] = "社交媒体",
            ["WebTVStreaming"] = "视频流媒体",
            ["WebSupport"] = "支持PANOMI"
        },
        ["hi"] = new()
        {
            ["ScanButton"] = "लॉन्चर और गेम खोजें",
            ["LaunchButton"] = "शुरू करें",
            ["LaunchingButton"] = "लॉन्च हो रहा है...",
            ["Library"] = "लाइब्रेरी",
            ["FilterAll"] = "सभी",
            ["FilterLaunchers"] = "लॉन्चर",
            ["FilterGames"] = "गेम्स",
            ["FilterButton"] = "फ़िल्टर",
            ["ResetFilters"] = "फ़िल्टर रीसेट",
            ["SearchPlaceholder"] = "खोजें...",
            ["TypeLauncher"] = "लॉन्चर",
            ["TypeGame"] = "गेम",
            ["FullscreenMode"] = "फ़ुल स्क्रीन",
            ["StartWithWindows"] = "Windows के साथ शुरू करें",
            ["MinimizeToTray"] = "त्वरित लॉन्च",
            ["QuickLaunchInfo"] = "PANOMI को सक्रिय रखता है ताकि तुरंत खुले",
            ["LanguageSetting"] = "भाषा",
            ["StatTotal"] = "कुल",
            ["StatLaunchers"] = "लॉन्चर",
            ["StatGames"] = "गेम्स",
            ["WebConsole"] = "कंसोल",
            ["WebLiveStreaming"] = "लाइव स्ट्रीमिंग",
            ["WebMisc"] = "विविध",
            ["WebPC"] = "पीसी",
            ["WebSocialMedia"] = "सोशल मीडिया",
            ["WebTVStreaming"] = "टीवी स्ट्रीमिंग",
            ["WebSupport"] = "PANOMI का समर्थन करें"
        }
    };
    
    public static void SetLanguage(string languageCode)
    {
        _currentLanguage = _strings.ContainsKey(languageCode) ? languageCode : "en-US";
    }
    
    public static string Get(string key)
    {
        if (_strings.TryGetValue(_currentLanguage, out var lang) && lang.TryGetValue(key, out var value))
            return value;
        if (_strings["en-US"].TryGetValue(key, out var fallback))
            return fallback;
        return key;
    }
}
